# Generated by Django 4.2 on 2023-06-13 19:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=11)),
                ('address', models.TextField()),
                ('loan_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('proposal_status', models.CharField(choices=[('unknown', 'UNKNOWN'), ('approved', 'APPROVED'), ('rejected', 'REJECTED')], default='unknown', max_length=8)),
            ],
        ),
    ]
