# Generated by Django 4.2 on 2023-06-14 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_loan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='proposal_status',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='unknown', max_length=8),
        ),
    ]
